### ISSUE TITLE
Detect Tor users by looking also at X-Forwarded-For header

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web-3.0#204]
This ticket is to detect Tor users, by redirecting them to .onion, also by looking also at X-Forwarded-For header.

This settings should be configurable (on/off).

**Comment by evilaliv3** [comment]
This would be needed in order to support revers proxies setups like: https://github.com/globaleaks/GlobaLeaks/issues/1128

**Comment by evilaliv3** [comment]
implemented!
