### ISSUE TITLE
Tor2web should inform the web client if is coming from Tor or not trough an HTTP header

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web-3.0#209]
This ticket is to improve Tor2web so that it should inform the web client if is coming from Tor or not trough an HTTP header.

The idea is that any application requiring to know if it's on Tor from it's client-side javascript resource, could inquiry any kind of Tor2web resources, looking at the response http header.

**Comment by fpietrosanti** [comment]
That maybe used too by GlobaLeaks software client

**Comment by evilaliv3** [comment]
implemented, currently Tor2web sets an header X-Check-Tor:true/false on every requests
