### ISSUE TITLE
Improve language detection via user-agent info for gettor

### ISSUE THREAD

**Issue by ilv** [globaleaks/Tor2web-3.0#217]
Regarding #168, I think we can follow [this](http://www.w3.org/International/questions/qa-lang-priorities.en.php) and [this](http://www.w3.org/International/articles/language-tags/), specially this idea: 

*"The basic rule here is that if your language preference list contains a language tag containing a hyphen, such as fr-CH (French as spoken in Switzerland), you should consider adding an additional language tag without the hyphen, ie. fr (French) in this case, immediately after."*

So, a basic algorithm for this could be as follows:
 1. Get language from User-Agent, let's say 'lc-LC'
 2. Check if 'lc-LC' matches any of the locales supported by the Tor Browser. If so, we are done.
 3. Take the first two letters before the dash ('lc' in this case) and check if it maches any of the locales supported by the Tor Browser. If so, we are done.
 4. Else, return default lc e.g. en-US.

For this purpose we should make some sort of mapping for en, es, pt, and zh to en-US, es-ES, pt-PT and zh-CN respectively. For instance:

  * We get the language from User-Agent: pt-BR
  * We check 2) and keep going
  * We check 3). Without the mapping pt => pt-PT we should have keep going to 4). With the mapping we are able to provide a more familiar language. 

This covers the case of a browser that is not configured properly e.g. have pt-BR and pt as preferred languages.

Thoughts? @fpietrosanti @evilaliv3

**Comment by evilaliv3** [comment]
thanks ilv your analisis is good;
it seems to me that it has only a case of failure that is the following

suppose the user locale is "es" , but right now TBB offers only es-ES, this way we will end providing en-US.

i've written the following algorithm that is like a charm on current Tor locales that are:

    ar
    de
    en-US
    es-ES
    fa
    fr
    it
    ko
    nl
    pl
    pt-PT
    ru
    tr
    vi
   zh-CN

analyze it with the following inputs and tell me what you think:
    ar -> will end providing ar
    es -> will end providing es-ES
    es-PT -> will end providing es-ES
    es-ES -> will end providing ES
    xx -> will end providing en-US

algorithm:

    lang = 'en-US

    if lc in supported-lc:
        ret = lc
    elif '-' in lc:
        lc = lc.split('-')[0]
        if lc in supported-lc:
            ret = lc
        elif:
            for lang in supported-lc:
                if '-' in lang:
                    lang = lang.split('-')[0]
                    if lc == lang:
                    ret = lc
                    break

what do you think?

**Comment by evilaliv3** [comment]
@ilv i've written a demo of the algorithm above to prove it agaist the cases i'm expecting:
https://gist.github.com/evilaliv3/5a9cd11eaa0cf60da425

any comment?

**Comment by ilv** [comment]
Great @evilaliv3, it seems that you have covered all the cases :) The algorithm works quite well, I've tested it with some extra inputs and all is good. Given the few locales supported by Tor Browser I think this will work perfectly fine.
